package tui

import (
	"fmt"
	"strings"

	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/x/ansi"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	extast "github.com/yuin/goldmark/extension/ast"
	"github.com/yuin/goldmark/text"
	"github.com/yuin/goldmark/util"
)

var conversationMarkdown = goldmark.New(goldmark.WithExtensions(extension.GFM))

type markdownTextStyle struct {
	fg, bg                          string
	bold, italic, underline, strike bool
}

type markdownRenderer struct {
	source []byte
	width  int
	colors palette
	lines  []string
}

// markdownLines parses untrusted conversation text and returns terminal-ready,
// width-bounded lines. Every escape in the result is generated by Lip Gloss;
// source text and parser-decoded values pass through safe before they are styled.
func markdownLines(source string, width int, colors palette) []string {
	if width <= 0 {
		return nil
	}
	input := []byte(safe(source))
	r := &markdownRenderer{source: input, width: width, colors: colors}
	doc := conversationMarkdown.Parser().Parse(text.NewReader(input))
	r.blocks(doc, "", "", true)
	for len(r.lines) > 0 && r.lines[len(r.lines)-1] == "" {
		r.lines = r.lines[:len(r.lines)-1]
	}
	if len(r.lines) == 0 {
		return []string{""}
	}
	return r.lines
}

func (r *markdownRenderer) styled(value string, s markdownTextStyle) string {
	value = safe(value)
	if value == "" || s == (markdownTextStyle{}) {
		return value
	}
	style := lipgloss.NewStyle()
	if s.fg != "" {
		style = style.Foreground(lipgloss.Color(s.fg))
	}
	if s.bg != "" {
		style = style.Background(lipgloss.Color(s.bg))
	}
	if s.bold {
		style = style.Bold(true)
	}
	if s.italic {
		style = style.Italic(true)
	}
	if s.underline {
		style = style.Underline(true)
	}
	if s.strike {
		style = style.Strikethrough(true)
	}
	return style.Render(value)
}

func (r *markdownRenderer) blocks(parent ast.Node, firstPrefix, restPrefix string, separate bool) {
	first := true
	for child := parent.FirstChild(); child != nil; child = child.NextSibling() {
		if child.Kind() == ast.KindLinkReferenceDefinition {
			continue
		}
		if separate && !first {
			r.blank()
		}
		prefix := restPrefix
		if first {
			prefix = firstPrefix
		}
		r.block(child, prefix, restPrefix)
		first = false
	}
}

func (r *markdownRenderer) block(node ast.Node, firstPrefix, restPrefix string) {
	switch n := node.(type) {
	case *ast.Paragraph, *ast.TextBlock:
		r.paragraph(r.inlineChildren(n, markdownTextStyle{}), firstPrefix, restPrefix)
	case *ast.Heading:
		fg := r.colors.violet
		style := markdownTextStyle{fg: fg, bold: true}
		if n.Level == 1 {
			style.underline = true
		}
		r.paragraph(r.inlineChildren(n, style), firstPrefix, restPrefix)
	case *ast.Blockquote:
		quote := r.styled("> ", markdownTextStyle{fg: r.colors.muted})
		r.blocks(n, firstPrefix+quote, restPrefix+quote, true)
	case *ast.List:
		r.list(n, firstPrefix, restPrefix)
	case *ast.ListItem:
		r.blocks(n, firstPrefix, restPrefix, false)
	case *ast.FencedCodeBlock:
		r.code(string(n.Lines().Value(r.source)), firstPrefix, restPrefix)
	case *ast.CodeBlock:
		r.code(string(n.Lines().Value(r.source)), firstPrefix, restPrefix)
	case *extast.Table:
		r.table(n, firstPrefix, restPrefix)
	case *ast.ThematicBreak:
		r.appendWrapped(r.styled("---", markdownTextStyle{fg: r.colors.muted}), firstPrefix, restPrefix)
	case *ast.HTMLBlock:
		value := string(n.Lines().Value(r.source))
		if n.HasClosure() {
			value += string(n.ClosureLine.Value(r.source))
		}
		r.paragraph(safe(value), firstPrefix, restPrefix)
	default:
		if node.HasChildren() {
			r.blocks(node, firstPrefix, restPrefix, true)
		}
	}
}

func (r *markdownRenderer) list(list *ast.List, prefix, restPrefix string) {
	index := 0
	for item := list.FirstChild(); item != nil; item = item.NextSibling() {
		if _, ok := item.(*ast.ListItem); !ok {
			continue
		}
		marker := "- "
		if list.IsOrdered() {
			start := list.Start
			if start < 1 {
				start = 1
			}
			marker = fmt.Sprintf("%d. ", start+index)
		}
		first := prefix + marker
		if index > 0 {
			first = restPrefix + marker
		}
		continuation := restPrefix + strings.Repeat(" ", ansi.StringWidth(marker))
		// The first block in a list item starts at its marker; later blocks
		// continue under the item text.
		if item.FirstChild() != nil {
			r.block(item.FirstChild(), first, continuation)
			for child := item.FirstChild().NextSibling(); child != nil; child = child.NextSibling() {
				r.block(child, continuation, continuation)
			}
		}
		index++
	}
}

func (r *markdownRenderer) paragraph(value, firstPrefix, restPrefix string) {
	r.appendWrapped(value, firstPrefix, restPrefix)
}

func (r *markdownRenderer) code(value, firstPrefix, restPrefix string) {
	value = strings.TrimSuffix(safe(value), "\n")
	lines := strings.Split(value, "\n")
	codeStyle := markdownTextStyle{fg: r.colors.cyan, bg: r.colors.panel}
	for i, line := range lines {
		first, rest := firstPrefix, restPrefix
		if i > 0 {
			first = restPrefix
		}
		r.appendWrapped(r.styled(line, codeStyle), first, rest)
	}
}

func (r *markdownRenderer) table(table *extast.Table, firstPrefix, restPrefix string) {
	rowIndex := 0
	for row := table.FirstChild(); row != nil; row = row.NextSibling() {
		header := false
		if _, ok := row.(*extast.TableHeader); ok {
			header = true
		}
		var cells []string
		for cell := row.FirstChild(); cell != nil; cell = cell.NextSibling() {
			if _, ok := cell.(*extast.TableCell); !ok {
				continue
			}
			style := markdownTextStyle{}
			if header {
				style = markdownTextStyle{bold: true, fg: r.colors.violet}
			}
			cells = append(cells, r.inlineChildren(cell, style))
		}
		if len(cells) == 0 {
			continue
		}
		prefix := restPrefix
		if rowIndex == 0 {
			prefix = firstPrefix
		}
		r.appendWrapped(strings.Join(cells, " | "), prefix, restPrefix)
		rowIndex++
		if header {
			separators := make([]string, len(cells))
			for i, cell := range cells {
				separators[i] = strings.Repeat("-", min(3, max(1, ansi.StringWidth(cell))))
			}
			r.appendWrapped(strings.Join(separators, "-+-"), restPrefix, restPrefix)
		}
	}
}

func (r *markdownRenderer) inlineChildren(parent ast.Node, inherited markdownTextStyle) string {
	var out strings.Builder
	for child := parent.FirstChild(); child != nil; child = child.NextSibling() {
		out.WriteString(r.inline(child, inherited))
	}
	return out.String()
}

func (r *markdownRenderer) inline(node ast.Node, inherited markdownTextStyle) string {
	switch n := node.(type) {
	case *ast.Text:
		value := string(n.Value(r.source))
		if !n.IsRaw() {
			decoded := util.UnescapePunctuations([]byte(value))
			decoded = util.ResolveNumericReferences(decoded)
			decoded = util.ResolveEntityNames(decoded)
			value = string(decoded)
		}
		if n.HardLineBreak() {
			return r.styled(strings.TrimRight(value, " \t\r\n"), inherited) + "\n"
		}
		if n.SoftLineBreak() {
			return r.styled(strings.TrimRight(value, " \t\r\n"), inherited) + " "
		}
		return r.styled(value, inherited)
	case *ast.String:
		return r.styled(string(n.Value), inherited)
	case *ast.Emphasis:
		style := inherited
		if n.Level > 1 {
			style.bold = true
		} else {
			style.italic = true
		}
		return r.inlineChildren(n, style)
	case *ast.CodeSpan:
		style := inherited
		style.fg, style.bg = r.colors.cyan, r.colors.panel
		return r.inlineChildren(n, style)
	case *ast.Link:
		style := inherited
		style.fg, style.underline = r.colors.blue, true
		label := r.inlineChildren(n, style)
		destination := safe(string(n.Destination))
		if destination != "" {
			label += r.styled(" <"+destination+">", markdownTextStyle{fg: r.colors.muted})
		}
		return label
	case *ast.Image:
		style := inherited
		style.fg, style.italic = r.colors.muted, true
		return r.styled("[image: ", markdownTextStyle{fg: r.colors.muted}) + r.inlineChildren(n, style) + r.styled("]", markdownTextStyle{fg: r.colors.muted})
	case *ast.AutoLink:
		style := inherited
		style.fg, style.underline = r.colors.blue, true
		return r.styled(string(n.Label(r.source)), style)
	case *ast.RawHTML:
		return safe(string(n.Segments.Value(r.source)))
	case *extast.Strikethrough:
		style := inherited
		style.fg, style.strike = r.colors.muted, true
		return r.inlineChildren(n, style)
	case *extast.TaskCheckBox:
		if n.IsChecked {
			return r.styled("[x] ", markdownTextStyle{fg: r.colors.green})
		}
		return r.styled("[ ] ", markdownTextStyle{fg: r.colors.muted})
	default:
		if node.HasChildren() {
			return r.inlineChildren(node, inherited)
		}
		return ""
	}
}

func (r *markdownRenderer) appendWrapped(value, firstPrefix, restPrefix string) {
	firstPrefix = boundedMarkdownPrefix(firstPrefix, r.width)
	restPrefix = boundedMarkdownPrefix(restPrefix, r.width)
	contentWidth := max(1, r.width-max(ansi.StringWidth(firstPrefix), ansi.StringWidth(restPrefix)))
	paragraphs := strings.Split(value, "\n")
	firstLine := true
	for _, paragraph := range paragraphs {
		wrapped := wrapMarkdownText(paragraph, contentWidth)
		for _, line := range wrapped {
			prefix := restPrefix
			if firstLine {
				prefix = firstPrefix
				firstLine = false
			}
			r.lines = append(r.lines, prefix+line)
		}
	}
}

// ansi.Wrap preserves SGR bytes but does not repeat an active style after a
// wrapped newline. Conversation rows are rendered independently, so close the
// style on each row and reopen it at the start of the continuation row.
func wrapMarkdownText(value string, width int) []string {
	wrapped := strings.Split(ansi.Wrap(value, max(1, width), ""), "\n")
	if len(wrapped) < 2 {
		return wrapped
	}
	lines := make([]string, 0, len(wrapped))
	active := ""
	for i, line := range wrapped {
		var b strings.Builder
		if i > 0 && active != "" {
			b.WriteString(active)
		}
		b.WriteString(line)
		active = markdownSGRState(active, line)
		if i+1 < len(wrapped) && active != "" {
			b.WriteString("\x1b[0m")
		}
		lines = append(lines, b.String())
	}
	return lines
}

func markdownSGRState(active, value string) string {
	for i := 0; i+1 < len(value); i++ {
		if value[i] != '\x1b' || value[i+1] != '[' {
			continue
		}
		end := strings.IndexByte(value[i+2:], 'm')
		if end < 0 {
			break
		}
		end += i + 2
		sequence := value[i : end+1]
		params := value[i+2 : end]
		if params == "" || params == "0" {
			active = ""
		} else if params == "0;" || strings.HasPrefix(params, "0;") {
			active = sequence
		} else {
			active += sequence
		}
		i = end
	}
	return active
}

func boundedMarkdownPrefix(prefix string, width int) string {
	if width <= 0 {
		return ""
	}
	if ansi.StringWidth(prefix) < width {
		return prefix
	}
	return ansi.Truncate(prefix, max(0, width-1), "")
}

func (r *markdownRenderer) blank() {
	if len(r.lines) > 0 && r.lines[len(r.lines)-1] != "" {
		r.lines = append(r.lines, "")
	}
}
