package agent

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"

	"github.com/muschterm/tui/apps/go/internal/protocol"
)

// Fixtures were generated by executing the pinned adapter's pure conversion
// functions. This is adapter-converter evidence, never a live question test.
func TestClaudeQuestionPinnedAdapterFixtures(t *testing.T) {
	raw, err := os.ReadFile("testdata/claude-questions-0.80.0.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Adapter string
		Samples []struct {
			Name     string
			Request  json.RawMessage
			Answers  []protocol.Answer
			Response json.RawMessage
		}
	}
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.Adapter != ClaudeQuestionVersion || len(fixture.Samples) != 3 {
		t.Fatal("unexpected fixture version or cases")
	}
	for _, sample := range fixture.Samples {
		t.Run(sample.Name, func(t *testing.T) {
			form, err := ParseClaudeQuestions("fixture", sample.Request)
			if err != nil {
				t.Fatal(err)
			}
			response, err := form.Response(sample.Answers)
			if err != nil {
				t.Fatal(err)
			}
			actual, _ := json.Marshal(response)
			var got, want any
			_ = json.Unmarshal(actual, &got)
			_ = json.Unmarshal(sample.Response, &want)
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("response %s does not match adapter fixture %s", actual, sample.Response)
			}
		})
	}
}
